### ISSUE TITLE
Needed content: Schedule

### ISSUE THREAD

**Issue by j0ma** [j0ma/mrl-2024-proceedings#5]

**Comment by j0ma** [comment]
Actually this is not needed(?). Will reopen if this changes.

**Comment by j0ma** [comment]
just kidding. schedule needs to become a YAML file like this:

```


- title: Title of the conference session, e.g. Opening Remarks
  start_time: Start time of the session as an ISO datestring.
  end_time: End time of the session as an ISO datestring.
  location: Location that the session is taking place in, e.g. Main Hall or Online
  chair: (opt) Name of the chair of the session, e.g. Jane Doe.
  url: (opt) URL to join or view the session, if applicable.
  papers:
  - id: Paper ID
    start_time: Optional start time of the paper slot as an ISO datestring.
    end_time: Optional start time of the paper slot as an ISO datestring.
# Or, if this is a session that is broken into subsessions:
- title: Title of the conference session, e.g. Opening Remarks
  start_time: Start time of the session as an ISO datestring.
  end_time: End time of the session as an ISO datestring.
  subsessions:
    - title: Title of the conference session, e.g. Opening Remarks
    start_time: Start time of the session as an ISO datestring.
    end_time: End time of the session as an ISO datestring.
    chair: (opt) Name of the chair of the session, e.g. Jane Doe.
    location: Location that the session is taking place in.
    papers:
    - id: Paper ID
      start_time: Optional start time of the paper slot as an ISO datestring.
      end_time: Optional start time of the paper slot as an ISO datestring.
```

**Comment by davidstap** [comment]
Hey I can create this but I'm waiting for input from Duygu / David (see email I just sent). After one of them responds I can create the YAML file and share it here.

**Comment by j0ma** [comment]
Sounds good, thanks @davidstap !

**Comment by davidstap** [comment]
I'm not sure where to put it, so I'll copy it here:

```
- title: Opening Remarks
  start_time: 2024-11-16T09:00:00
  end_time: 2024-11-16T09:10:00
  location: Workshop Room
- title: Invited Talk by Karen Livescu
  start_time: 2024-11-16T09:10:00
  end_time: 2024-11-16T09:50:00
  location: Workshop Room
  speaker: Karen Livescu
- title: Invited Talk by Hila Gonen
  start_time: 2024-11-16T09:50:00
  end_time: 2024-11-16T10:30:00
  location: Workshop Room
  speaker: Hila Gonen
- title: Coffee Break
  start_time: 2024-11-16T10:30:00
  end_time: 2024-11-16T11:00:00
  location: Break Area
- title: Poster Session
  start_time: 2024-11-16T11:00:00
  end_time: 2024-11-16T12:30:00
  location: Poster Hall
- title: Lunch Break
  start_time: 2024-11-16T12:30:00
  end_time: 2024-11-16T14:00:00
  location: Dining Area
- title: Shared Task Session
  start_time: 2024-11-16T14:00:00
  end_time: 2024-11-16T14:30:00
  location: Workshop Room
  subsessions:
    - title: Findings Paper
      start_time: 2024-11-16T14:00:00
      end_time: 2024-11-16T14:15:00
      location: Workshop Room
    - title: Winning Team Presentation
      start_time: 2024-11-16T14:15:00
      end_time: 2024-11-16T14:30:00
      location: Workshop Room
- title: Best Paper Session
  start_time: 2024-11-16T14:30:00
  end_time: 2024-11-16T15:30:00
  location: Workshop Room
  subsessions:
    - title: Best Paper
      start_time: 2024-11-16T14:30:00
      end_time: 2024-11-16T15:00:00
      location: Workshop Room
    - title: Honorable Mentions
      start_time: 2024-11-16T15:00:00
      end_time: 2024-11-16T15:30:00
      location: Workshop Room
- title: Coffee Break
  start_time: 2024-11-16T15:30:00
  end_time: 2024-11-16T16:00:00
  location: Break Area
- title: Invited Talk by Sebastian Ruder
  start_time: 2024-11-16T16:00:00
  end_time: 2024-11-16T16:50:00
  location: Workshop Room
  speaker: Sebastian Ruder
- title: Closing Remarks
  start_time: 2024-11-16T16:50:00
  end_time: 2024-11-16T17:00:00
  location: Workshop Room
```
